### ISSUE TITLE
[Bug Report] <Warlock Pet dps in details>

### ISSUE THREAD

**Issue by Dragowow** [Luckyone961/LuckyoneUI#14]
**Description**
Warlock pets dps isnt merging in details and I couldnt figure out how to fix it

**Version Number**
2.45

**Steps to Reproduce**
< Provide all the steps necessary to reproduce the problem >

Step 1:Just play the game
Step 2:
Step 3:
Step 4:

**Expected Behavior**
dps from pet should merge

**Actual Behavior**
no mergey

**Only ElvUI + LuckyoneUI enabled**
< Please provide information about whether or not you can reproduce it >
< when ElvUI and LuckyoneUI are the only addons enabled >

**Blizzard Issue?**
< Please test if you can reproduce the issue with 0 addons enabled >
< Include screenshot of how it looks if possible >

**Additional Information**
< Please provide any additional information here >

**Error Log**
< If you received an error then please post it in the empty space below >
< so that the error is wrapped in the 3 backquotes (before and after) >
```

```

**Comment by Repooc** [comment]
This sounds like a question for details, not LuckoneUI as he isn't the addon author of details and doesn't have control of any changes details may be doing.

**Comment by Dragowow** [comment]
It was working before I went through the installation process for Luckyone and works if I turn all addons minus details off and go to a default profile.

**Comment by Repooc** [comment]
so tldr; you dont like LuckyoneUI details profile. that may be how he likes it as the setup is for how he prefers his layout. I would suggest to not use the details profile lucky provides, and tweak the details settings to your liking, or import lucky's settings then go to details and find the option to make it report pets the way you would like (assuming the rest of the details profile of his you like)

**Comment by Repooc** [comment]
Waiting on Flam from details to respond to see if they changed anything but I am assuming Lucky's profile is how Lucky intends/wants his profile. I will report back once Flam confirms they changed/or didnt change anything for it to be like this.

**Comment by Dragowow** [comment]
No it's supposed to automatically merge pet damage only hunters have a separate setting to my understanding. I do like how its setup but I cant see how much damage I am doing like that. I will just close the ticket. I tried looking for an option or something to tweak like I said but couldnt find anything. Sorry to bother you no reason to be a dick I will close the ticket and fuck off.

**Comment by Dragowow** [comment]
xd

**Comment by Repooc** [comment]
Not being a dick, just stating facts. It's his profile for his use that he has available for others to use. If something is not how you like it, you are free to modify it to fit your needs. I know there were issues details were having with combat log changes as one of the devs is in our Tukui/ElvUI community discord. I pinged him to see if he was aware of any issues you have stated as Lucky has not altered his profile string since May 8th. So any "issues" you are having will most likely be something done on Details or Blizzards end, which in turn could have borked the import string but is most likely not the case.

**Comment by Repooc** [comment]
I have pointed Flam to this ticket but I do know there has been changes back and forth with realmnames and I know he had issues with bit.band and such which would not be something on Luckyone as he only provides a profile, only way it would be on lucky is something has changed enough in details that would require a new profile string export. You taking that as being a dick is on you when I only stated facts.

**Comment by Flamanis** [comment]
Luckyone applies a profile. He does not control our parser.

Blizzard made a change on ptr to include realm names for all players. Which messed up a lot of our core functionality and we've been fixing it this previous week.

Blizzard reverted their change yesterday. So we had to revert our changes.


If you have issues with Details, do bring them up in our Discord and not in an unrelated addons github issues. https://discord.gg/AGSzAZX
