### ISSUE TITLE
Battleground Queue / button sometimes hidden

### ISSUE THREAD

**Issue by linkx2252** [Luckyone961/LuckyoneUI#16]
In season of Discovery, sometimes the queue / battleground button is hidden. Maybe an issue with square minimap buttons?

Sometimes I see it, sometimes I don't. 99% of the time when I queue I don't see it.

If I do /edebug on , I do see the button, which leads me to believe it is a LUI issue?

**Comment by Luckyone961** [comment]
I assume its because of ProjectAzilroka / Square Minimap Buttons - he is currently not really maintaining his AddOns and I'd recommend using [MinimapButtonButton](https://www.curseforge.com/wow/addons/minimapbuttonbutton) for non-Retail versions of WoW instead (I'm doing the same)
